# Generated by Django 4.0.3 on 2022-07-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
