# Generated by Django 4.0.5 on 2022-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': ('product',), 'verbose_name_plural': 'products'},
        ),
    ]
